import pandas as pd
import os

def generate_html():
    # 讀取資料
    csv_file = "ING-003.csv"
    if not os.path.exists(csv_file):
        print(f"找不到 {csv_file}")
        return

    df = pd.read_csv(csv_file)

    # 建立 HTML 模板
    html_content = f"""
    <!DOCTYPE html>
    <html lang="zh-TW">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FIRDI-L 食材進貨儀表板</title>
        <!-- 使用 Bootstrap 5 與 DataTables -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
        <style>
            body {{ background-color: #f8f9fa; padding: 20px; }}
            .container {{ background: white; padding: 30px; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; margin-bottom: 20px; }}
            .table-container {{ margin-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="text-center">🍎 FIRDI-L 食材進貨查詢系統</h1>
            <p class="text-muted text-center">這是由 CSV 自動生成的靜態網頁介面</p>
            
            <div class="row text-center mb-4">
                <div class="col-md-4">
                    <div class="card p-3 border-primary">
                        <h5>總項目數</h5>
                        <h2 class="text-primary">{len(df)}</h2>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-3 border-success">
                        <h5>產地總數</h5>
                        <h2 class="text-success">{len(df['產地'].unique())}</h2>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-3 border-info">
                        <h5>主要供應商</h5>
                        <h2 class="text-info">{df['供應商'].mode()[0]}</h2>
                    </div>
                </div>
            </div>

            <div class="table-container">
                <table id="myTable" class="table table-striped table-hover" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            {" ".join([f"<th>{col}</th>" for col in df.columns])}
                        </tr>
                    </thead>
                    <tbody>
                        {" ".join([
                            "<tr>" + "".join([f"<td>{val}</td>" for val in row]) + "</tr>"
                            for _, row in df.iterrows()
                        ])}
                    </tbody>
                </table>
            </div>
            
            <footer class="mt-5 text-center text-muted">
                <p>&copy; 2026 FIRDI-L Project. Generated by TraceEyeAI.</p>
            </footer>
        </div>

        <!-- 引入 JavaScript -->
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
        <script>
            $(document).ready(function() {{
                $('#myTable').DataTable({{
                    "language": {{
                        "url": "//cdn.datatables.net/plug-ins/1.13.6/i18n/zh-HANT.json"
                    }},
                    "pageLength": 10,
                    "order": []
                }});
            }});
        </script>
    </body>
    </html>
    """

    # 存檔
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)
    print("成功生成 index.html！")

if __name__ == "__main__":
    generate_html()
